name: Build, test and deploy Python webapp


on:
  workflow_dispatch:

permissions:
  contents: read # access to check out code and install dependencies


jobs:
  build-and-test:
    runs-on: [ubuntu-latest]

    



    steps:
          
      - name: Checkout
        uses: actions/checkout@v5.0.0
 

      - name: Setup Python
        uses: actions/setup-python@v6.0.0
        with:
          python-version: '3.13'
          cache: 'pip'
