name: Build, test and deploy Python webapp


on:
  workflow_dispatch:


jobs:
  build-and-test:
    runs-on: [ubuntu-latest]



    steps:
          
      - name: Checkout
        uses: actions/checkout@v5.0.0
 