name: gitleaks in python code 
on:
  pull_request:
  push:
  workflow_dispatch:
  # schedule:
  #   - cron: "0 4 * * *" # run once a day at 4 AM


permissions:
  contents: read

jobs:
  scan:
    name: gitleaks
    runs-on: ubuntu-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Scan leaks in code repo
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          