name: auto test the python code


on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read # access to check out code and install dependencies


jobs:
  testing:
    runs-on: [ubuntu-latest]
    strategy:
      matrix:
        python-version: ["3.12"]

    
    steps:
          
      - name: Checkout
        uses: actions/checkout@v5.0.0
 

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6.0.0
        with:
          python-version: ${{ matrix.python-version }} 
          cache: 'pip'
          

      - name: Install dependencies
        run : |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: test python code
        run : pytest
      
        

      
          
